version: 0.2
phases:
  install:
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo pre_build steps...
      - aws --version
      - $(aws ecr get-login --region us-west-1 --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
  